export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'; //estar logeado
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADVERT_LOADED_REQUEST = 'ADVERT_LOADED_REQUEST'; //accion leer anuncios
export const ADVERT_LOADED_SUCCESS = 'ADVERT_LOADED_SUCCESS';
export const ADVERT_LOADED_FAILURE = 'ADVERT_LOADED_FAILURE';

export const ADVER_LOADED_REQUEST = 'ADVER_LOADED_REQUEST'; //accion leer un anuncio
export const ADVER_LOADED_SUCCESS = 'ADVER_LOADED_SUCCESS';
export const ADVER_LOADED_FAILURE = 'ADVER_LOADED_FAILURE';

export const ADVERT_CREATED = 'ADVERT_CREATED'; //creacion de anuncio

export const TAGS_REQUEST = 'TAGS_REQUEST';
export const TAGS_SUCCESS = 'TAGS_SUCCESS';
export const TAGS_FAILURE = 'TAGS_FAILURE';

export const ADD_ADVERTS_REQUEST = 'ADD_ADVERTS_REQUEST';
export const ADD_ADVERTS_SUCCESS = 'ADD_ADVERTS_SUCCESS';
export const ADD_ADVERTS_FAILURE = 'ADD_ADVERTS_FAILURE';

export const ADVERT_CREATED_SUCCESS = 'ADVERT_CREATED_SUCCESS';
export const ADVERT_CREATED_FAILURE = 'ADVERT_CREATED_FAILURE';
export const ADVERT_CREATED_REQUEST = 'ADVERT_CREATED_REQUEST';

export const ADVERT_DELETED_SUCCESS = 'ADVERT_DELETED_SUCCESS';
export const ADVERT_DELETED_REQUEST = 'ADVERT_DELETED_REQUEST';
export const ADVERT_DELETED_FAILURE = 'ADVERT_DELETED_FAILURE';
